### ISSUE TITLE
Compatibility?

### ISSUE THREAD

**Issue by DrQbz** [applenana/AP-AMS#10]
Hi!
What printers is this project compatible with? Bambu P1P by any chance?

**Comment by applenana** [comment]
It depends on which branch you use. In theory, branches like 'main' and 'SerialOnly', which are based on the Bambu MQTT interface, can be used with any Bambu model including Bambu P1P. However, FakeAMSLite simulates AMSLITE, so it can only be used with the Bambu A series.
