### ISSUE TITLE
HA分支中回抽延时无法修改

### ISSUE THREAD

**Issue by xz0609** [applenana/AP-AMS#12]
用HA修改下回抽延时且串口输出修改到了指定值，刷新HA页面后没有变化还是原来的值。另外耗材类型跟温度都能修改。

**Comment by PJJ8826** [comment]
还有‘回抽时间’希望能和‘进料等待时间’同步，不然P系列没法用

**Comment by applenana** [comment]
> 还有‘回抽时间’希望能和‘进料等待时间’同步，不然P系列没法用

大概率不会更改这个，因为各通道是独立的

**Comment by applenana** [comment]
将会在2.4版本中修复

**Comment by applenana** [comment]
https://github.com/applenana/AP-AMS/releases/tag/v2.4
