### ISSUE TITLE
连接拓竹打印机问题

### ISSUE THREAD

**Issue by YSSN95384** [applenana/AP-AMS#15]
![image](https://github.com/user-attachments/assets/1ca03de9-d1b0-4d33-9f8f-9d1e46509849)
显示连接成功但是还在循环里面一直循环
![image](https://github.com/user-attachments/assets/114f614a-e3d6-45ab-a636-0796f39e8c35)

**Comment by applenana** [comment]
我注意到你mqtt地址使用的是url的格式，无论是mqtt地址还是拓竹地址，使用的都是ip地址的格式，即xxx.xxx.xxx.xxx(如192.168.31.1)同时也不需要带端口，mqtt端口1883，请再次检查你的配置是否符合此规定
---
至于说为什么显示连接成功，但又继续连接，可能是序列号填写错误造成的
