### ISSUE TITLE
[建议]希望增加保存耗材类型与颜色的功能

### ISSUE THREAD

**Issue by HelloTheAsia** [applenana/AP-AMS#6]
希望可以加入保存耗材类型与颜色的功能,类似于下图
<img width="450" alt="image" src="https://github.com/applenana/AP-AMS/assets/26612794/a95f5d92-23ff-4ab7-b299-a68c73830288">
项目使用homeassistant，数据可视化,拓竹机器可以非常方便的接入homeassistant,也有很完善的图形界面.这样可以更加方便的在homeassistant进行可视化,已快速查看打印机与AP-AMS的运行情况

参考链接:
https://github.com/greghesp/ha-bambulab
https://www.wolfwithsword.com/bambulab-home-assistant-dashboard/

**Comment by applenana** [comment]
已经在 [releasev2.3](https://github.com/applenana/AP-AMS/releases/tag/v2.3) 中实现
